---
- name: "2.3.7.1 (L1) Ensure 'Interactive logon: Do not display last user name' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: DontDisplayLastUserName
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_7_1 is not defined or rule_2_3_7_1 is defined) and not rule_2_3_7_1
  tags:
    - level1
    - patch
    - rule_2.3.7.1


- name: "2.3.7.2 (L1) Ensure 'Interactive logon: Do not require CTRL+ALT+DEL' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: DisableCAD
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_7_2 is not defined or rule_2_3_7_2 is defined) and not rule_2_3_7_2
  tags:
    - level1
    - patch
    - rule_2.3.7.2


- name: "2.3.7.3 (L1)  Ensure 'Interactive logon: Machine inactivity limit' is set to '900 or fewer second(s), but not 0'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: InactivityTimeoutSecs
    data: 900
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_7_3 is not defined or rule_2_3_7_3 is defined) and not rule_2_3_7_3
  tags:
    - level1
    - patch
    - rule_2.3.7.3


- name: "2.3.7.4 (L1) Configure 'Interactive logon: Message text for users attempting to log on'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: LegalNoticeText
    data: 'This system is for the use of Takeda authorized users only. By using this system all users acknowledge notice of and agree to comply with Takedas Global Code of Conduct and Global Acceptable Use of Technology Policy All Takeda supplied computers laptops tablets mobile phones systems are and remain at all times the property of Takeda. Takeda may review monitor audit and intercept all data created stored received or sent via such equipment or systems for the purposes of administering the network and identifying investigating or resolving suspected security threats or breaches to the extent legally permitted. This Notice applies to the extent permissible under and subject at all times to applicable law.","-------------------------------------------------------------------------","本システムは、タケダの許可を受けたユーザー専用です。すべてのユーザーは、本システムを使用することにより、タケダのグローバル行動規準およびテクノロジーの利用に関するグルーバルポリシーを確認し、それに従うことに同意したとみなされます。タケダが支給したコンピュータ、ノートパソコン、タブレット、携帯電話、システムおよびこれらの機器に保存されたデータは、常に会社の資産とみなされます。タケダは、これらのシステムで作成、受信、または送信したすべてのメッセージを許可された法の範囲でレビュー、モニター、監査、傍受する場合があります。目的は、ネットワークの管理や疑わしいセキュリティの脅威や情報漏洩を識別し、調査および解決することです。この通知は、許可された法の範囲で常に適用されます。'
    type: string
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_7_4 is not defined or rule_2_3_7_4 is defined) and not rule_2_3_7_4
  tags:
    - level1
    - patch
    - rule_2.3.7.4


- name: "2.3.7.5 (L1) Configure 'Interactive logon: Message title for users attempting to log on'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: LegalNoticeCaption
    data: "Takeda Information Security Notice"
    type: string
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_7_5 is not defined or rule_2_3_7_5 is defined) and not rule_2_3_7_5
  tags:
    - level1
    - patch
    - rule_2.3.7.5

# - name: "2.3.7.6 (L2) Ensure 'Interactive logon: Number of previous logons to cache (in case domain controller is not available)' is set to '4 or fewer logon(s)' (MS only)"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
#     name: CachedLogonsCount
#     data: 4
#     type: string

- name: "2.3.7.7 (L1) Ensure 'Interactive logon: Prompt user to change password before expiration' is set to 'between 5 and 14 days'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: PasswordExpiryWarning
    data: 14
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_7_7 is not defined or rule_2_3_7_7 is defined) and not rule_2_3_7_7
  tags:
    - level1
    - patch
    - rule_2.3.7.7


- name: "2.3.7.8 (L1) Ensure 'Interactive logon: Require Domain Controller Authentication to unlock workstation' is set to 'Enabled' (MS only)"
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows Nt\Currentversion\Winlogon
    name: ForceUnlockLogon
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_7_8 is not defined or rule_2_3_7_8 is defined) and not rule_2_3_7_8
  tags:
    - level1
    - patch
    - rule_2.3.7.8

- name: "2.3.7.9 (L1) Ensure 'Interactive logon: Smart card removal behavior' is set to 'Lock Workstation' or higher"
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows Nt\Currentversion\Winlogon
    name: scremoveoption
    data: 1
    type: string
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_7_9 is not defined or rule_2_3_7_9 is defined) and not rule_2_3_7_9
  tags:
    - level1
    - patch
    - rule_2.3.7.9