---
- name: "2.3.1.1 (L1) Ensure 'Accounts: Administrator account status' is set to 'Disabled' (MS only)"
  win_security_policy:
    section: System Access
    key: EnableAdminAccount
    value: 1
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_1_1 is not defined or rule_2_3_1_1 is defined) and not rule_2_3_1_1
  tags:
    - level1
    - patch
    - rule_2.3.1.1

- name: "2.3.1.2 (L1) Ensure 'Accounts: Block Microsoft accounts' is set to 'Users can't add or log on with Microsoft accounts'"
  win_regedit:
    data: 3
    name: NoConnectedUser
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_1_2 is not defined or rule_2_3_1_2 is defined) and not rule_2_3_1_2
  tags:
    - level1
    - patch
    - rule_2.3.1.2

- name: "2.3.1.3 (L1) Ensure 'Accounts: Guest account status' is set to 'Disabled' (MS only)"
  win_security_policy:
    section: System Access
    key: EnableGuestAccount
    value: 0
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_1_3 is not defined or rule_2_3_1_3 is defined) and not rule_2_3_1_3
  tags:
    - level1
    - patch
    - rule_2.3.1.3

- name: "2.3.1.4 (L1) Ensure 'Accounts: Limit local account use of blank passwords to console logon only' is set to 'Enabled'"
  win_regedit:
    data: 1
    name: LimitBlankPasswordUse
    path: HKCU:\SYSTEM\CurrentControlSet\Control\Lsa
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_1_4 is not defined or rule_2_3_1_4 is defined) and not rule_2_3_1_4
  tags:
    - level1
    - patch
    - rule_2.3.1.4

# - name: "2.3.1.5 (L1) Configure 'Accounts: Rename administrator account'"
#   win_security_policy:
#     section: System Access
#     key: newadministratorname
#     value: "User_Adm"
#   when:
#     - win2016cis_level1 is defined and win2016cis_level1
#     - (rule_2_3_1_5 is not defined or rule_2_3_1_5 is defined) and not rule_2_3_1_5
#   tags:
#     - level1
#     - patch
#     - rule_2.3.1.5


# - name: "2.3.1.6 (L1) Configure 'Accounts: Rename guest account'"
#   win_security_policy:
#     section: System Access
#     key: NewGuestName
#     value: "User_Guest"
#   when:
#     - win2016cis_level1 is defined and win2016cis_level1
#     - (rule_2_3_1_6 is not defined or rule_2_3_1_6 is defined) and not rule_2_3_1_6
#   tags:
#     - level1
#     - patch
#     - rule_2.3.1.6
