---
- name: "18.8.3.1 (L1) Ensure 'Include command line in process creation events' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit
    name: ProcessCreationIncludeCmdLine_Enabled
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_3_1 is not defined or rule_18_8_3_1 is defined) and not rule_18_8_3_1
  tags:
    - level1
    - patch
    - rule_18.8.3.1

- name: "18.8.4.1 Ensure 'Encryption Oracle Remediation' Encryption Oracle Remediation'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\CredSSP\Parameters
    name: AllowEncryptionOracle
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_4_1 is not defined or rule_18_8_4_1 is defined) and not rule_18_8_4_1
  tags:
    - level1
    - patch
    - rule_18.8.4.1

- name: "18.8.4.2 (L1) Ensure 'Remote host allows delegation of non-exportable credentials' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CredentialsDelegation
    name: AllowProtectedCreds
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_4_2 is not defined or rule_18_8_4_2 is defined) and not rule_18_8_4_2
  tags:
    - level1
    - patch
    - rule_18.8.4.2

# - name: "Deviceguard 18.8.5.1"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
#     name: EnableVirtualizationBasedSecurity
#     data: 1
#     type: dword
# 
# - name: "Deviceguard 18.8.5.2"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
#     name: RequirePlatformSecurityFeatures
#     data: 3
#     type: dword
# 
# - name: "Deviceguard 18.8.5.3"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
#     name: HypervisorEnforcedCodeIntegrity
#     data: 1
#     type: dword
# 
# - name: "Deviceguard 18.8.5.4"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
#     name: LsaCfgFlags
#     data: 1
#     type: dword
# 
- name: "18.8.5.6 (NG) Ensure 'Turn On Virtualization Based Security: Credential Guard Configuration' (DC Only)"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard
    name: LsaCfgFlags
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_5_6 is not defined or rule_18_8_5_6 is defined) and not rule_18_8_5_6
  tags:
    - level1
    - patch
    - rule_18.8.5.6

- name: "18.8.14.1 (L1)  Ensure 'Boot-Start Driver Initialization Policy' is set to 'Enabled: Good, unknown and bad but critical'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Policies\EarlyLaunch
    name: DriverLoadPolicy
    data: 3
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_14_1 is not defined or rule_18_8_14_1 is defined) and not rule_18_8_14_1
  tags:
    - level1
    - patch
    - rule_18.8.14.1

- name: "18.8.21.2 (L1) Ensure 'Configure registry policy processing: Do not apply during periodic background processing' is set to 'Enabled: FALSE'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Group Policy\{35378EAC-683F-11D2-A89A-00C04FBBCFA2}
    name: NoBackgroundPolicy
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_21_2 is not defined or rule_18_8_21_2 is defined) and not rule_18_8_21_2
  tags:
    - level1
    - patch
    - rule_18.8.21.2

- name: "18.8.21.3 (L1) Ensure 'Configure registry policy processing: Process even if the Group Policy objects have not changed' is set to 'Enabled: TRUE'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Group Policy\{35378EAC-683F-11D2-A89A-00C04FBBCFA2}
    name: NoGPOListChanges
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_21_3 is not defined or rule_18_8_21_3 is defined) and not rule_18_8_21_3
  tags:
    - level1
    - patch
    - rule_18.8.21.3

- name: "18.8.21.4 (L1) Ensure 'Continue experiences on this device' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
    name: EnableCdp
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_21_4 is not defined or rule_18_8_21_4 is defined) and not rule_18_8_21_4
  tags:
    - level1
    - patch
    - rule_18.8.21.4

- name: "18.8.21.5 (L1) Ensure 'Turn off background refresh of Group Policy' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: DisableBkGndGroupPolicy
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_21_5 is not defined or rule_18_8_21_5 is defined) and not rule_18_8_21_5
  tags:
    - level1
    - patch
    - rule_18.8.21.5
  
- name: "18.8.22.1.1 (L2) Ensure 'Turn off downloading of print drivers over HTTP' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Printers
    name: DisableWebPnPDownload
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_22_1_1 is not defined or rule_18_8_22_1_1 is defined) and not rule_18_8_22_1_1
  tags:
    - level1
    - patch
    - rule_18.8.22.1.1

# - name: "18.8.22.1.2 (L2) Ensure Turn off handwriting personalization data sharing is set to Enabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\TabletPC
#     name: PreventHandwritingDataSharing
#     data: 1
#     type: dword

# - name: "18.8.22.1.3 (L2) Ensure Turn off handwriting recognition error reporting is set to Enabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\HandwritingErrorReports
#     name: PreventHandwritingErrorReports
#     data: 1
#     type: dword

# - name: "18.8.22.1.4 (L2) Ensure Turn off Internet Connection Wizard if URL connection is referring to Microsoft.com is set to Enabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Internet Connection Wizard
#     name: ExitOnMSICW
#     data: 1
#     type: dword

- name: "18.8.22.1.5 (L2) Ensure Turn off Internet download for Web publishing and online ordering wizards is set to Enabled"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
    name: NoWebServices
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_22_1_5 is not defined or rule_18_8_22_1_5 is defined) and not rule_18_8_22_1_5
  tags:
    - level1
    - patch
    - rule_18.8.22.1.5

# - name: "18.8.22.1.6 (L2) Ensure Turn off printing over HTTP is set to Enabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
#     name: DisableHTTPPrinting
#     data: 1
#     type: dword

# - name: "18.8.22.1.7 (L2) Ensure Turn off Registration if URL connection is referring to Microsoft.com is set to Enabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Registration Wizard Control
#     name: NoRegistration
#     data: 1
#     type: dword

# - name: "18.8.22.1.8 (L2) Ensure Turn off Search Companion content file updates is set to Enabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\SearchCompanion
#     name: DisableContentFileUpdates
#     data: 1
#     type: dword

# - name: "18.8.22.1.9 (L2) Ensure Turn off the 'Order Prints' picture task is set to Enabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
#     name: NoOnlinePrintsWizard
#     data: 1
#     type: dword

# - name: "18.8.22.1.11 (L2) Ensure Turn off the Windows Messenger Customer Experience Improvement Program is set to Enabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Messenger\Client
#     name: CEIP
#     data: 2
#     type: dword

# - name: "18.8.22.1.12 (L2) Ensure Turn off Windows Customer Experience Improvement Program is set to Enabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\SQMClient\Windows
#     name: CEIPEnable
#     data: 0
#     type: dword

# - name: "18.8.22.1.13 (L2) Ensure Turn off Windows Error Reporting is set to Enabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting
#     name: Disabled
#     data: 1
#     type: dword

# - name: "18.8.22.1.13 (L2) Ensure Turn off Windows Error Reporting is set to Enabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\PCHealth\ErrorReporting
#     name: DoReport
#     data: 0
#     type: dword

# - name: "18.8.25.1 (L2) Ensure Support device authentication using certificate is set to Enabled: Automatic - DevicePKInitBehavior"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\kerberos\parameters
#     name: DevicePKInitBehavior
#     data: 0
#     type: dword

# - name: "18.8.25.1 (L2) Ensure Support device authentication using certificate is set to Enabled: Automatic - DevicePKInitEnabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\kerberos\parameters
#     name: DevicePKInitEnabled
#     data: 1
#     type: dword

- name: "18.8.28.1 (L1) Ensure 'Block user from showing account details on sign-in' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
    name: BlockUserFromShowingAccountDetailsOnSignin
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_28_1 is not defined or rule_18_8_28_1 is defined) and not rule_18_8_28_1
  tags:
    - level1
    - patch
    - rule_18.8.28.1

- name: "18.8.28.2 (L1) Ensure 'Do not display network selection UI' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
    name: DontDisplayNetworkSelectionUI
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_28_2 is not defined or rule_18_8_28_2 is defined) and not rule_18_8_28_2
  tags:
    - level1
    - patch
    - rule_18.8.28.2

- name: "18.8.28.3 (L1) Ensure 'Do not enumerate connected users on domain-joined computers' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
    name: DontEnumerateConnectedUsers
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_28_3 is not defined or rule_18_8_28_3 is defined) and not rule_18_8_28_3
  tags:
    - level1
    - patch
    - rule_18.8.28.3

- name: "18.8.28.4 (L1) Ensure 'Enumerate local users on domain-joined computers' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
    name: EnumerateLocalUsers
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_28_4 is not defined or rule_18_8_28_4 is defined) and not rule_18_8_28_4
  tags:
    - level1
    - patch
    - rule_18.8.28.4

- name: "18.8.28.5 (L1) Ensure 'Turn off app notifications on the lock screen' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
    name: DisableLockScreenAppNotifications
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_28_5 is not defined or rule_18_8_28_5 is defined) and not rule_18_8_28_5
  tags:
    - level1
    - patch
    - rule_18.8.28.5

- name: "18.8.28.6 (L1) Ensure 'Turn off picture password sign-in' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
    name: BlockDomainPicturePassword
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_28_6 is not defined or rule_18_8_28_6 is defined) and not rule_18_8_28_6
  tags:
    - level1
    - patch
    - rule_18.8.28.6

- name: "18.8.28.7 (L1) Ensure 'Turn on convenience PIN sign-in' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
    name: AllowDomainPINLogon
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_28_7 is not defined or rule_18_8_28_7 is defined) and not rule_18_8_28_7
  tags:
    - level1
    - patch
    - rule_18.8.28.7

- name: "18.8.34.6.3 (L2) Ensure Require a password when a computer wakes (on battery) is set to Enabled"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51
    name: DCSettingIndex
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_34_6_3 is not defined or rule_18_8_34_6_3 is defined) and not rule_18_8_34_6_3
  tags:
    - level1
    - patch
    - rule_18.8.34.6.3

- name: "18.8.33.6.4 (L2) Ensure Require a password when a computer wakes (plugged in) is set to Enabled"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51
    name: ACSettingIndex
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_34_6_4 is not defined or rule_18_8_34_6_4 is defined) and not rule_18_8_34_6_4
  tags:
    - level1
    - patch
    - rule_18.8.34.6.4

- name: "18.8.36.1 (L1) Ensure 'Configure Offer Remote Assistance' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    name: fAllowUnsolicited
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_36_1 is not defined or rule_18_8_36_1 is defined) and not rule_18_8_36_1
  tags:
    - level1
    - patch
    - rule_18.8.36.1

- name: "18.8.36.2 (L1) Ensure 'Configure Solicited Remote Assistance' is set to 'Disabled"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    name: fAllowToGetHelp
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_36_2 is not defined or rule_18_8_36_2 is defined) and not rule_18_8_36_2
  tags:
    - level1
    - patch
    - rule_18.8.36.2

- name: "18.8.37.1 (L1) Ensure 'Enable RPC Endpoint Mapper Client Authentication' is set to 'Enabled' (MS only)"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Rpc
    name: EnableAuthEpResolution
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_8_37_1 is not defined or rule_18_8_37_1 is defined) and not rule_18_8_37_1
  tags:
    - level1
    - patch
    - rule_18.8.37.1

# - name: "18.8.36.2 (L2) Ensure Restrict Unauthenticated RPC clients is set to Enabled: Authenticated (MS only)"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Rpc
#     name: RestrictRemoteClients
#     data: 1
#     type: dword
# 
# - name: "18.8.44.5.1 (L2) Ensure Microsoft Support Diagnostic Tool: Turn on MSDT interactive communication with support provider is set to Disabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\ScriptedDiagnosticsProvider\Policy
#     name: DisableQueryRemoteServer
#     data: 0
#     type: dword

# - name: "18.8.44.11.1 (L2) Ensure Enable/Disable PerfTrack is set to Disabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WDI\{9c5a40da-b965-4fc3-8781-88dd50a6299d}
#     name: ScenarioExecutionEnabled
#     data: 0
#     type: dword

# - name: "18.8.46.1 (L2) Ensure Turn off the advertising ID is set to Enabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\policies\Microsoft\Windows\AdvertisingInfo
#     name: DisabledByGroupPolicy
#     data: 1
#     type: dword

# - name: "18.8.49.1.1 (L2) Ensure Enable Windows NTP Client is set to Enabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\W32Time\TimeProviders\NtpClient
#     name: Enabled
#     data: 1
#     type: dword

# - name: "18.8.49.1.2 (L2) Ensure Enable Windows NTP Server is set to Disabled (MS only)"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\W32Time\TimeProviders\NtpServer
#     name: Enabled
#     data: 0
#     type: dword


