---
- name: "2.3.4.1 (L1) Ensure 'Devices: Allowed to format and eject removable media' is set to 'Administrators'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: AllocateDASD
    data: 0
    type: string
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_4_1 is not defined or rule_2_3_4_1 is defined) and not rule_2_3_4_1
  tags:
    - level1
    - patch
    - rule_2.3.4.1


- name: "2.3.4.2 (L1) Ensure 'Devices: Prevent users from installing printer drivers' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Print\Providers\LanMan Print Services\Servers
    name: AddPrinterDrivers
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_4_2 is not defined or rule_2_3_4_2 is defined) and not rule_2_3_4_2
  tags:
    - level1
    - patch
    - rule_2.3.4.2

