---
- name: "2.3.11.1 (L1) Ensure 'Network security: Allow Local System to use computer identity for NTLM' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: UseMachineId
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_11_1 is not defined or rule_2_3_11_1 is defined) and not rule_2_3_11_1
  tags:
    - level1
    - patch
    - rule_2.3.11.1


- name: "2.3.11.2 (L1) Ensure 'Network security: Allow LocalSystem NULL session fallback' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
    name: AllowNullSessionFallback
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_11_2 is not defined or rule_2_3_11_2 is defined) and not rule_2_3_11_2
  tags:
    - level1
    - patch
    - rule_2.3.11.2


- name: "2.3.11.3 (L1) Ensure 'Network Security: Allow PKU2U authentication requests to this computer to use online identities' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\pku2u
    name: AllowOnlineID
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_11_3 is not defined or rule_2_3_11_3 is defined) and not rule_2_3_11_3
  tags:
    - level1
    - patch
    - rule_2.3.11.3


- name: "2.3.11.4 (L1)  Ensure 'Network security: Configure encryption types allowed for Kerberos' is set to 'RC4_HMAC_MD5, AES128_HMAC_SHA1, AES256_HMAC_SHA1, Future encryption types'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Kerberos\Parameters
    name: SupportedEncryptionTypes
    data: 2147483640
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_11_4 is not defined or rule_2_3_11_4 is defined) and not rule_2_3_11_4
  tags:
    - level1
    - patch
    - rule_2.3.11.4


- name: "2.3.11.5 (L1) Ensure 'Network security: Do not store LAN Manager hash value on next password change' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: NoLMHash
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_11_5 is not defined or rule_2_3_11_5 is defined) and not rule_2_3_11_5
  tags:
    - level1
    - patch
    - rule_2.3.11.5

# - name: "2.3.11.6 (L1) Ensure 'Network security: Force logoff when logon hours expire' is set to 'Enabled'"
#   win_regedit:
#     path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
#     name: EnableForcedLogOff
#     data: 1
#     type: dword

- name: "2.3.11.7 (L1) Ensure 'Network security: LAN Manager authentication level' is set to 'Send NTLMv2 response only. Refuse LM & NTLM'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: LmCompatibilityLevel
    data: 5
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_11_7 is not defined or rule_2_3_11_7 is defined) and not rule_2_3_11_7
  tags:
    - level1
    - patch
    - rule_2.3.11.7


- name: "2.3.11.8 (L1) Ensure 'Network security: LDAP client signing requirements' is set to 'Negotiate signing' or higher"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LDAP
    name: LDAPClientIntegrity
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_11_8 is not defined or rule_2_3_11_8 is defined) and not rule_2_3_11_8
  tags:
    - level1
    - patch
    - rule_2.3.11.8


- name: "2.3.11.9 (L1)  Ensure 'Network security: Minimum session security for NTLM SSP based (including secure RPC) clients' is set to 'Require NTLMv2 session security, Require 128-bit encryption'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
    name: NTLMMinClientSec
    data: 537395200
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_11_9 is not defined or rule_2_3_11_9 is defined) and not rule_2_3_11_9
  tags:
    - level1
    - patch
    - rule_2.3.11.9


- name: "2.3.11.10 (L1)  Ensure 'Network security: Minimum session security for NTLM SSP based (including secure RPC) servers' is set to 'Require NTLMv2 session security, Require 128-bit encryption'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
    name: NTLMMinServerSec
    data: 537395200
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_11_10 is not defined or rule_2_3_11_10 is defined) and not rule_2_3_11_10
  tags:
    - level1
    - patch
    - rule_2.3.11.10

