---
- name: "2.3.17.1 (L1) Ensure 'User Account Control: Admin Approval Mode for the Built-in Administrator account' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: FilterAdministratorToken
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_17_1 is not defined or rule_2_3_17_1 is defined) and not rule_2_3_17_1
  tags:
    - level1
    - patch
    - rule_2.3.17.1


- name: "2.3.17.2 (L1) Ensure 'User Account Control: Behavior of the elevation prompt for administrators in Admin Approval Mode' is set to 'Prompt for consent on the secure desktop' "
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: ConsentPromptBehaviorAdmin
    data: 2
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_17_2 is not defined or rule_2_3_17_2 is defined) and not rule_2_3_17_2
  tags:
    - level1
    - patch
    - rule_2.3.17.2


- name: "2.3.17.3 (L1) Ensure 'User Account Control: Behavior of the elevation prompt for standard users' is set to 'Automatically deny elevation requests'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: ConsentPromptBehaviorUser
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_17_3 is not defined or rule_2_3_17_3 is defined) and not rule_2_3_17_3
  tags:
    - level1
    - patch
    - rule_2.3.17.3


- name: "2.3.17.4 (L1) Ensure 'User Account Control: Detect application installations and prompt for elevation' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: EnableInstallerDetection
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_17_4 is not defined or rule_2_3_17_4 is defined) and not rule_2_3_17_4
  tags:
    - level1
    - patch
    - rule_2.3.17.4


- name: "2.3.17.5 (L1) Ensure 'User Account Control: Only elevate UIAccess applications that are installed in secure locations' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: EnableSecureUIAPaths
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_17_5 is not defined or rule_2_3_17_5 is defined) and not rule_2_3_17_5
  tags:
    - level1
    - patch
    - rule_2.3.17.5


- name: "2.3.17.6 (L1) Ensure 'User Account Control: Run all administrators in Admin Approval Mode' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: EnableLUA
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_17_6 is not defined or rule_2_3_17_6 is defined) and not rule_2_3_17_6
  tags:
    - level1
    - patch
    - rule_2.3.17.6


- name: "2.3.17.7 (L1) Ensure 'User Account Control: Switch to the secure desktop when prompting for elevation' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: PromptOnSecureDesktop
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_17_7 is not defined or rule_2_3_17_7 is defined) and not rule_2_3_17_7
  tags:
    - level1
    - patch
    - rule_2.3.17.7


- name: "2.3.17.8 (L1) Ensure 'User Account Control: Virtualize file and registry write failures to per-user locations' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: EnableVirtualization
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_17_8 is not defined or rule_2_3_17_8 is defined) and not rule_2_3_17_8
  tags:
    - level1
    - patch
    - rule_2.3.17.8

