---
- name: "18.3.1 (L1) Ensure 'Apply UAC restrictions to local accounts on network logons' is set to 'Enabled' (MS only)"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: LocalAccountTokenFilterPolicy
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_3_1 is not defined or rule_18_3_1 is defined) and not rule_18_3_1
  tags:
    - level1
    - patch
    - rule_18.3.1

- name: "18.3.2 (L1) Ensure 'Configure SMB v1 client driver' is set to 'Enabled: Disable driver'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\mrxsmb10
    name: Start
    data: 4
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_3_2 is not defined or rule_18_3_2 is defined) and not rule_18_3_2
  tags:
    - level1
    - patch
    - rule_18.3.2

- name: "18.3.3 (L1) Ensure 'Configure SMB v1 server' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
    name: SMB1
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_3_3 is not defined or rule_18_3_3 is defined) and not rule_18_3_3
  tags:
    - level1
    - patch
    - rule_18.3.3

- name: "18.3.4 (L1) Ensure 'Enable Structured Exception Handling Overwrite Protection (SEHOP)' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel
    name: DisableExceptionChainValidation
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_3_4 is not defined or rule_18_3_4 is defined) and not rule_18_3_4
  tags:
    - level1
    - patch
    - rule_18.3.4

# - name: "18.3.5 (L1) Ensure 'Extended Protection for LDAP Authentication (Domain Controllers only)' is set to 'Enabled'"
#   win_regedit:
#     path: HKLM:\SYSTEM\CurrentControlSet\Services\NTDS\Parameters
#     name: LdapEnforceChannelBinding
#     data: 2
#     type: dword
#   when:
#     - win2016cis_level1 is defined and win2016cis_level1
#     - (rule_18_3_5 is not defined or rule_18_3_5 is defined) and not rule_18_3_5
#   tags:
#     - level1
#     - patch
#     - rule_18.3.5

- name: "18.3.7 (L1) Ensure 'WDigest Authentication' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest
    name: UseLogonCredential
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_3_7 is not defined or rule_18_3_7 is defined) and not rule_18_3_7
  tags:
    - level1
    - patch
    - rule_18.3.7

- name: "18.4.1 (L1) Ensure 'MSS: (AutoAdminLogon) Enable Automatic Logon (not recommended)' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: AutoAdminLogon
    data: 0
    type: string
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_4_1 is not defined or rule_18_4_1 is defined) and not rule_18_4_1
  tags:
    - level1
    - patch
    - rule_18.4.1

- name: "18.4.2 (L1)  Ensure 'MSS: (DisableIPSourceRouting IPv6) IP source routing protection level (protects against packet spoofing)' is set to 'Enabled: Highest protection, source routing is completely disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
    name: DisableIPSourceRouting
    data: 2
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_4_2 is not defined or rule_18_4_2 is defined) and not rule_18_4_2
  tags:
    - level1
    - patch
    - rule_18.4.2

- name: "18.4.3 (L1)  Ensure 'MSS: (DisableIPSourceRouting) IP source routing protection level (protects against packet spoofing)' is set to 'Enabled: Highest protection, source routing is completely disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
    name: DisableIPSourceRouting
    data: 2
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_4_3 is not defined or rule_18_4_3 is defined) and not rule_18_4_3
  tags:
    - level1
    - patch
    - rule_18.4.3

- name: "18.4.4 (L1) Ensure 'MSS: (EnableICMPRedirect) Allow ICMP redirects to override OSPF generated routes' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
    name: EnableICMPRedirect
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_4_4 is not defined or rule_18_4_4 is defined) and not rule_18_4_4
  tags:
    - level1
    - patch
    - rule_18.4.4

# - name: "18.4.5 (L2) Ensure 'MSS: (KeepAliveTime) How often keep-alive packets are sent in milliseconds' is set to 'Enabled: 300,000 or 5 minutes (recommended)'"
#   win_regedit:
#     path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
#     name: KeepAliveTime
#     data: 300000
#     type: dword
#   when: cis_level_2 == true

- name: "18.4.6 (L1) Ensure 'MSS: (NoNameReleaseOnDemand) Allow the computer to ignore NetBIOS name release requests except from WINS servers' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters
    name: NoNameReleaseOnDemand
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_4_6 is not defined or rule_18_4_6 is defined) and not rule_18_4_6
  tags:
    - level1
    - patch
    - rule_18.4.6

# - name: "18.4.7 (L2) Ensure MSS: (PerformRouterDiscovery) Allow IRDP to detect and configure Default Gateway addresses (could lead to DoS) is set to Disabled"
#   win_regedit:
#     path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
#     name: PerformRouterDiscovery
#     data: 0
#     type: dword
#   when: cis_level_2 == true

- name: "18.4.8 (L1) Ensure 'MSS: (SafeDllSearchMode) Enable Safe DLL search mode (recommended)' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager
    name: SafeDllSearchMode
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_4_8 is not defined or rule_18_4_8 is defined) and not rule_18_4_8
  tags:
    - level1
    - patch
    - rule_18.4.8

- name: "18.4.9 (L1) Ensure 'MSS: (ScreenSaverGracePeriod) The time in seconds before the screen saver grace period expires (0 recommended)' is set to 'Enabled: 5 or fewer seconds'"
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: ScreenSaverGracePeriod
    data: 5
    type: string
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_4_9 is not defined or rule_18_4_9 is defined) and not rule_18_4_9
  tags:
    - level1
    - patch
    - rule_18.4.9

- name: "18.4.12 (L1) Ensure 'MSS: (WarningLevel) Percentage threshold for the security event log at which the system will generate a warning' is set to 'Enabled: 90% or less'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Eventlog\Security
    name: WarningLevel
    data: 90
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_4_12 is not defined or rule_18_4_12 is defined) and not rule_18_4_12
  tags:
    - level1
    - patch
    - rule_18.4.12
