---
- name: "19.7.4.1 (L1) Ensure 'Do not preserve zone information in file attachments' is set to 'Disabled'"
  win_regedit:
    path: HKU:\{{ item }}\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Attachments
    name: SaveZoneInformation
    data: 2
    type: dword
  loop: "{{ hku.sub_keys | select('match', '^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$') | list }}"
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_19_7_4_1 is not defined or rule_19_7_4_1 is defined) and not rule_19_7_4_1
  tags:
    - level1
    - patch
    - rule_19.7.4.1

- name: "19.7.4.2 (L1) Ensure 'Notify antivirus programs when opening attachments' is set to 'Enabled'"
  win_regedit:
    path: HKU:\{{ item }}\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Attachments
    name: ScanWithAntiVirus
    data: 3
    type: dword
  loop: "{{ hku.sub_keys | select('match', '^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$') | list }}"
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_19_7_4_2 is not defined or rule_19_7_4_2 is defined) and not rule_19_7_4_2
  tags:
    - level1
    - patch
    - rule_19.7.4.2

- name: "19.7.7.1 (L2) Ensure Configure Windows spotlight on Lock Screen is set to Disabled"
  win_regedit:
    path: HKU:\{{ item }}\Software\Policies\Microsoft\Windows\CloudContent
    name: ConfigureWindowsSpotlight
    data: 2
    type: dword
  loop: "{{ hku.sub_keys | select('match', '^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$') | list }}"
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_19_7_7_1 is not defined or rule_19_7_7_1 is defined) and not rule_19_7_7_1
  tags:
    - level1
    - patch
    - rule_19.7.7.1

- name: "19.7.7.2 (L1) Ensure 'Do not suggest third-party content in Windows spotlight' is set to 'Enabled'"
  win_regedit:
    path: HKU:\{{ item }}\Software\Policies\Microsoft\Windows\CloudContent
    name: DisableThirdPartySuggestions
    data: 1
    type: dword
  loop: "{{ hku.sub_keys | select('match', '^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$') | list }}"
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_19_7_7_2 is not defined or rule_19_7_7_2 is defined) and not rule_19_7_7_2
  tags:
    - level1
    - patch
    - rule_19.7.7.2

# - name: "19.7.7.3 (L2) Ensure 'Do not use diagnostic data for tailored experiences' is set to 'Enabled'"
#   win_regedit:
#     path: HKU:\{{ item }}\Software\Policies\Microsoft\Windows\CloudContent
#     name: DisableTailoredExperiencesWithDiagnosticData
#     data: 1
#     type: dword
#   loop: "{{ hku.sub_keys | select('match', '^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$') | list }}"
# 
# - name: "19.7.7.4 (L2) Ensure Turn off all Windows spotlight features is set to Enabled'"
#   win_regedit:
#     path: HKU:\{{ item }}\Software\Policies\Microsoft\Windows\CloudContent
#     name: DisableWindowsSpotlightFeatures
#     data: 1
#     type: dword
#   loop: "{{ hku.sub_keys | select('match', '^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$') | list }}"
# 
- name: "19.7.26.1 (L1) Ensure 'Prevent users from sharing files within their profile.' is set to 'Enabled'"
  win_regedit:
    path: HKU:\{{ item }}\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
    name: NoInplaceSharing
    data: 1
    type: dword
  loop: "{{ hku.sub_keys | select('match', '^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$') | list }}"
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_19_7_26_1 is not defined or rule_19_7_26_1 is defined) and not rule_19_7_26_1
  tags:
    - level1
    - patch
    - rule_19.7.26.1

- name: "19.7.41.1 (L1) Ensure 'Always install with elevated privileges' is set to 'Disabled'"
  win_regedit:
    path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windows\Installer
    name: AlwaysInstallElevated
    data: 0
    type: dword
  loop: "{{ hku.sub_keys | select('match', '^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$') | list }}"
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_19_7_41_1 is not defined or rule_19_7_41_1 is defined) and not rule_19_7_41_1
  tags:
    - level1
    - patch
    - rule_19.7.41.1

# - name: "19.7.44.2.1 (L2) Ensure Prevent Codec Download is set to Enabled"
#   win_regedit:
#     path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\WindowsMediaPlayer
#     name: PreventCodecDownload
#     data: 1
#     type: dword
#   loop: "{{ hku.sub_keys | select('match', '^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$') | list }}"
# 