# ---
- name: "2.3.5.1 (L1) Ensure 'Domain controller: Allow server operators to schedule tasks' is set to 'Disabled' (DC only)"
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Lsa
    name: SubmitControl
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_5_1 is not defined or rule_2_3_5_1 is defined) and not rule_2_3_5_1
    - domain_joined_only is defined and domain_joined_only
  tags:
    - level1
    - patch
    - rule_2.3.5.1
    - domain_joined_only

# - name: "2.3.5.2 (L1) Ensure 'Domain controller: LDAP server signing requirements' is set to 'Require signing' (DC only)"
#   win_regedit:
#     path: HKLM:\System\CurrentControlSet\Services\NTDS\Parameters
#     name: LDAPServerIntegrity
#     data: 2
#     type: dword

- name: "2.3.5.3 (L1) Ensure 'Domain controller: Refuse machine account password changes' is set to 'Disabled' (DC only) "
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters
    name: RefusePasswordChange
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_5_3 is not defined or rule_2_3_5_3 is defined) and not rule_2_3_5_3
    - domain_joined_only is defined and domain_joined_only
  tags:
    - level1
    - patch
    - rule_2.3.5.3
    - domain_joined_only