---
- name: "2.3.9.1 (L1)  Ensure 'Microsoft network server: Amount of idle time required before suspending session' is set to '15 or fewer minute(s), but not 0"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
    name: AutoDisconnect
    data: 15
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_9_1 is not defined or rule_2_3_9_1 is defined) and not rule_2_3_9_1
  tags:
    - level1
    - patch
    - rule_2.3.9.1


- name: "2.3.9.2 (L1) Ensure 'Microsoft network server: Digitally sign communications (always)' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
    name: RequireSecuritySignature
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_9_2 is not defined or rule_2_3_9_2 is defined) and not rule_2_3_9_2
  tags:
    - level1
    - patch
    - rule_2.3.9.2


- name: "2.3.9.3 (L1) Ensure 'Microsoft network server: Digitally sign communications (if client agrees)' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
    name: EnableSecuritySignature
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_9_3 is not defined or rule_2_3_9_3 is defined) and not rule_2_3_9_3
  tags:
    - level1
    - patch
    - rule_2.3.9.3


- name: "2.3.9.4 (L1) Ensure 'Microsoft network server: Disconnect clients when logon hours expire' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
    name: EnableForcedLogoff
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_9_4 is not defined or rule_2_3_9_4 is defined) and not rule_2_3_9_4
  tags:
    - level1
    - patch
    - rule_2.3.9.4


# - name: "2.3.9.5 (L1) Ensure 'Microsoft network server: Server SPN target name validation level' is set to 'Accept if provided by client' or higher (MS only)"
#   win_regedit:
#     path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
#     name: SMBServerNameHardeningLevel
#     data: 1
#     type: dword

