---
- name: "2.2.1 (L1) Ensure 'Access Credential Manager as a trusted caller' is set to 'No One'"
  win_user_right:
    name: SeTrustedCredManAccessPrivilege
    users: []
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_1 is not defined or rule_2_2_1 is defined) and not rule_2_2_1
  tags:
    - level1
    - patch
    - rule_2.2.1

- name: "2.2.2 2.2.3 (L1) Ensure 'Access this computer from the network' is set to 'Administrators, Authenticated Users, ENTERPRISE DOMAIN CONTROLLERS' (DC only)"
  win_user_right:
    name: SeNetworkLogonRight
    users:
        - Administrators
        - Authenticated Users
        - ENTERPRISE DOMAIN CONTROLLERS
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_2 is not defined or rule_2_2_2 is defined) and not rule_2_2_2
    - (rule_2_2_3 is not defined or rule_2_2_3 is defined) and not rule_2_2_3
  tags:
    - level1
    - patch
    - rule_2.2.2
    - rule_2.2.3

- name: "2.2.4 (L1) Ensure 'Act as part of the operating system' is set to 'No One'"
  win_user_right:
    name: SeTcbPrivilege
    users: []
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_4 is not defined or rule_2_2_4 is defined) and not rule_2_2_4
  tags:
    - level1
    - patch
    - rule_2.2.4

- name: "2.2.5 (L1) Ensure 'Add workstations to domain' is set to 'Administrators' (DC only)"
  win_user_right:
    name: SeMachineAccountPrivilege
    users: Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_5 is not defined or rule_2_2_5 is defined) and not rule_2_2_5
    - domain_joined_only is defined and domain_joined_only
  tags:
    - level1
    - patch
    - rule_2.2.5
    - domain_joined_only

- name: "2.2.6 (L1) Ensure 'Adjust memory quotas for a process' is set to 'Administrators, LOCAL SERVICE, NETWORK SERVICE'"
  win_user_right:
    name: SeIncreaseQuotaPrivilege
    users:
        - Administrators
        - Local Service
        - Network Service
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_6 is not defined or rule_2_2_6 is defined) and not rule_2_2_6
  tags:
    - level1
    - patch
    - rule_2.2.6

- name: "2.2.7 (L1) Ensure 'Allow log on locally' is set to 'Administrators'"
  win_user_right:
    name: SeInteractiveLogonRight
    users:
        - Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_7 is not defined or rule_2_2_7 is defined) and not rule_2_2_7
  tags:
    - level1
    - patch
    - rule_2.2.7

- name: "2.2.8 & 2.2.9 (L1) Ensure Allow log on through Remote Desktop Services is set to Administrators DC only"
  win_user_right:
    name: SeRemoteInteractiveLogonRight
    users:
        - Administrators
        - Remote Desktop Users
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_8 is not defined or rule_2_2_8 is defined) and not rule_2_2_8
    - (rule_2_2_9 is not defined or rule_2_2_9 is defined) and not rule_2_2_9
  tags:
    - level1
    - patch
    - rule_2.2.8
    - rule_2.2.9

- name: "2.2.10 (L1) Ensure 'Back up files and directories' is set to 'Administrators'"
  win_user_right:
    name: SeBackupPrivilege
    users:
        - Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_10 is not defined or rule_2_2_10 is defined) and not rule_2_2_10
  tags:
    - level1
    - patch
    - rule_2.2.10

- name: "2.2.11 (L1) Ensure 'Change the system time' is set to 'Administrators, LOCAL SERVICE'"
  win_user_right:
    name: SeSystemTimePrivilege
    users:
        - Administrators
        - Local Service
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_11 is not defined or rule_2_2_11 is defined) and not rule_2_2_11
  tags:
    - level1
    - patch
    - rule_2.2.11

- name: "2.2.12 (L1) Ensure 'Change the time zone' is set to 'Administrators, LOCAL SERVICE'"
  win_user_right:
    name: SeTimeZonePrivilege
    users:
        - Administrators
        - Local Service
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_12 is not defined or rule_2_2_12 is defined) and not rule_2_2_12
  tags:
    - level1
    - patch
    - rule_2.2.12

- name: "2.2.13 (L1) Ensure 'Create a pagefile' is set to 'Administrators'"
  win_user_right:
    name: SeCreatePagefilePrivilege
    users:
        - Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_13 is not defined or rule_2_2_13 is defined) and not rule_2_2_13
  tags:
    - level1
    - patch
    - rule_2.2.13

- name: "2.2.14 (L1) Ensure 'Create a token object' is set to 'No One'"
  win_user_right:
    name: SeCreateTokenPrivilege
    users: []
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_14 is not defined or rule_2_2_14 is defined) and not rule_2_2_14
  tags:
    - level1
    - patch
    - rule_2.2.14

- name: "2.2.15 (L1) Ensure 'Create global objects' is set to 'Administrators, LOCAL SERVICE, NETWORK SERVICE, SERVICE'"
  win_user_right:
    name: SeCreateGlobalPrivilege
    users:
        - Administrators
        - Local Service
        - Network Service
        - Service
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_15 is not defined or rule_2_2_15 is defined) and not rule_2_2_15
  tags:
    - level1
    - patch
    - rule_2.2.15

- name: "2.2.16 (L1) Ensure 'Create permanent shared objects' is set to 'No One'"
  win_user_right:
    name: SeCreatePermanentPrivilege
    users: []
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_16 is not defined or rule_2_2_16 is defined) and not rule_2_2_16
  tags:
    - level1
    - patch
    - rule_2.2.16

- name: "2.2.17 (L1) Ensure 'Create symbolic links' is set to 'Administrators' (DC only)"
  win_user_right:
    name: SeCreateSymbolicLinkPrivilege
    users:
        - Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_17 is not defined or rule_2_2_17 is defined) and not rule_2_2_17
  tags:
    - level1
    - patch
    - rule_2.2.17

- name: "2.2.19 (L1) Ensure 'Debug programs' is set to 'Administrators'"
  win_user_right:
    name: SeDebugPrivilege
    users:
        - Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_19 is not defined or rule_2_2_19 is defined) and not rule_2_2_19
  tags:
    - level1
    - patch
    - rule_2.2.19

# - name: "2.2.20 (L1) Ensure 'Deny access to this computer from the network' is set to 'Guests' (DC only)"
#   win_user_right:
#     name: SeDenyNetworkLogonRight
#     users:
#         - Guests
#     action: set
#   when:
#     - win2016cis_level1 is defined and win2016cis_level1
#     - (rule_2_2_20 is not defined or rule_2_2_20 is defined) and not rule_2_2_20
#   tags:
#     - level1
#     - patch
#     - rule_2.2.20

- name: "2.2.21 (L1) Ensure 'Deny access to this computer from the network' is set to 'Guests, Local account and member of Administrators group' (MS only)"
  win_user_right:
    name: SeDenyNetworkLogonRight
    users:
        - Guests
        # - Local Account
        # - Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_21 is not defined or rule_2_2_21 is defined) and not rule_2_2_21
  tags:
    - level1
    - patch
    - rule_2.2.21

- name: "2.2.22 (L1) Ensure 'Deny log on as a batch job' to include 'Guests'"
  win_user_right:
    name: SeDenyBatchLogonRight
    users:
        - Guests
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_22 is not defined or rule_2_2_22 is defined) and not rule_2_2_22
  tags:
    - level1
    - patch
    - rule_2.2.22

- name: "2.2.23 (L1) Ensure 'Deny log on as a service' to include 'Guests'"
  win_user_right:
    name: SeDenyServiceLogonRight
    users:
        - Guests
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_23 is not defined or rule_2_2_22 is defined) and not rule_2_2_22
  tags:
    - level1
    - patch
    - rule_2.2.23

- name: "2.2.24 (L1) Ensure 'Deny log on locally' to include 'Guests'"
  win_user_right:
    name: SeDenyInteractiveLogonRight
    users:
        - Guests
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_24 is not defined or rule_2_2_24 is defined) and not rule_2_2_24
  tags:
    - level1
    - patch
    - rule_2.2.24

- name: "2.2.25 (L1) Ensure 'Deny log on through Remote Desktop Services' is set to 'Guests' (DC only)"
  win_user_right:
    name: SeDenyRemoteInteractiveLogonRight
    users:
        - Guests
        # - Local Account
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_25 is not defined or rule_2_2_25 is defined) and not rule_2_2_25
  tags:
    - level1
    - patch
    - rule_2.2.25

# - name: "2.2.26 (L1) Ensure 'Deny log on through Remote Desktop Services' is set to 'Guests, Local account' (MS only)"
#   win_user_right:
#     name: SeDenyRemoteInteractiveLogonRight
#     users:
#         - Guests
#         - Local Account
#     action: set
#   when:
#     - win2016cis_level1 is defined and win2016cis_level1
#     - (rule_2_2_26 is not defined or rule_2_2_26 is defined) and not rule_2_2_26
#   tags:
#     - level1
#     - patch
#     - rule_2.2.26


- name: "2.2.27 (L1) Ensure 'Enable computer and user accounts to be trusted for delegation' is set to 'Administrators' (DC only)"
  win_user_right:
    name: SeEnableDelegationPrivilege
    users: Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_27 is not defined or rule_2_2_27 is defined) and not rule_2_2_27
    - domain_joined_only is defined and domain_joined_only
  tags:
    - level1
    - patch
    - rule_2.2.27
    - domain_joined_only

- name: "2.2.28 (L1) Ensure 'Enable computer and user accounts to be trusted for delegation' is set to 'No One' (MS only)"
  win_user_right:
    name: SeEnableDelegationPrivilege
    users: []
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_28 is not defined or rule_2_2_28 is defined) and not rule_2_2_28
    - non_domain_joined_only is defined and non_domain_joined_only
  tags:
    - level1
    - patch
    - rule_2.2.28
    - non_domain_joined_only

- name: "2.2.29 (L1) Ensure 'Force shutdown from a remote system' is set to 'Administrators'"
  win_user_right:
    name: SeRemoteShutdownPrivilege
    users:
        - Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_29 is not defined or rule_2_2_29 is defined) and not rule_2_2_29
  tags:
    - level1
    - patch
    - rule_2.2.29

- name: "2.2.30 (L1) Ensure 'Generate security audits' is set to 'LOCAL SERVICE, NETWORK SERVICE'"
  win_user_right:
    name: SeAuditPrivilege
    users:
        - Local Service
        - Network Service
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_30 is not defined or rule_2_2_30 is defined) and not rule_2_2_30
  tags:
    - level1
    - patch
    - rule_2.2.30

- name: "2.2.31 (L1) Ensure 'Impersonate a client after authentication' is set to 'Administrators, LOCAL SERVICE, NETWORK SERVICE, SERVICE' (DC only)"
  win_user_right:
    name: SeImpersonatePrivilege
    users:
        - Administrators
        - Local Service
        - Network Service
        - Service
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_31 is not defined or rule_2_2_31 is defined) and not rule_2_2_31
    - domain_joined_only is defined and domain_joined_only
  tags:
    - level1
    - patch
    - rule_2.2.31
    - domain_joined_only

- name: "2.2.32 (L1) Ensure 'Impersonate a client after authentication (MS Only)'"
  win_user_right:
    name: SeImpersonatePrivilege
    users:
        - Administrators
        - IIS_IUSRS
        - Local Service
        - Network Service
        - Service
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_32 is not defined or rule_2_2_32 is defined) and not rule_2_2_32
    - non_domain_joined_only is defined and non_domain_joined_only
  tags:
    - level1
    - patch
    - rule_2.2.32
    - non_domain_joined_only

- name: "2.2.33 (L1) Ensure 'Increase scheduling priority' is set to 'Administrators'"
  win_user_right:
    name: SeIncreaseBasePriorityPrivilege
    users:
        - Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_33 is not defined or rule_2_2_33 is defined) and not rule_2_2_33
  tags:
    - level1
    - patch
    - rule_2.2.33

- name: "2.2.34 (L1) Ensure 'Load and unload device drivers' is set to 'Administrators'"
  win_user_right:
    name: SeLoadDriverPrivilege
    users:
        - Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_34 is not defined or rule_2_2_34 is defined) and not rule_2_2_34
  tags:
    - level1
    - patch
    - rule_2.2.34

- name: "2.2.35 (L1) Ensure 'Lock pages in memory' is set to 'No One'"
  win_user_right:
    name: SeLockMemoryPrivilege
    users: []
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_35 is not defined or rule_2_2_35 is defined) and not rule_2_2_35
  tags:
    - level1
    - patch
    - rule_2.2.32

# - name: "2.2.36 (L2) Ensure 'Log on as a batch job' is set to 'Administrators' (DC Only)"
#   win_user_right:
#     name: SeBatchLogonRight
#     users: Administrators
#     action: set

# - name: "2.2.37 (L1) Ensure 'Manage auditing and security log' is set to 'Administrators' and (when Exchange is running in the environment) `Exchange Servers' (DC only)"
#   win_user_right:
#       name: SeSecurityPrivilege
#       users:
#           - Administrators
#       action: set

- name: "2.2.38 (L1) Ensure 'Manage auditing and security log' is set to 'Administrators' (MS only)"
  win_user_right:
    name: SeSecurityPrivilege
    users:
        - Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_38 is not defined or rule_2_2_38 is defined) and not rule_2_2_38
  tags:
    - level1
    - patch
    - rule_2.2.38

- name: "2.2.39 (L1) Ensure 'Modify an object label' is set to 'No One'"
  win_user_right:
    name: SeReLabelPrivilege
    users: []
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_39 is not defined or rule_2_2_39 is defined) and not rule_2_2_39
  tags:
    - level1
    - patch
    - rule_2.2.39

- name: "2.2.40 (L1) Ensure 'Modify firmware environment values' is set to 'Administrators'"
  win_user_right:
    name: SeSystemEnvironmentPrivilege
    users:
        - Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_40 is not defined or rule_2_2_40 is defined) and not rule_2_2_40
  tags:
    - level1
    - patch
    - rule_2.2.40

- name: "2.2.41 (L1) Ensure 'Perform volume maintenance tasks' is set to 'Administrators'"
  win_user_right:
    name: SeManageVolumePrivilege
    users:
        - Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_41 is not defined or rule_2_2_41 is defined) and not rule_2_2_41
  tags:
    - level1
    - patch
    - rule_2.2.41

- name: "2.2.42 (L1) Ensure 'Profile single process' is set to 'Administrators'"
  win_user_right:
    name: SeProfileSingleProcessPrivilege
    users:
        - Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_42 is not defined or rule_2_2_42 is defined) and not rule_2_2_42
  tags:
    - level1
    - patch
    - rule_2.2.42

- name: "2.2.43 (L1) Ensure 'Profile system performance' is set to 'Administrators, NT SERVICE WdiServiceHost'"
  win_user_right:
    name: SeSystemProfilePrivilege
    users:
        - Administrators
        - NT SERVICE\WdiServiceHost
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_43 is not defined or rule_2_2_43 is defined) and not rule_2_2_43
  tags:
    - level1
    - patch
    - rule_2.2.43

- name: "2.2.44 (L1) Ensure 'Replace a process level token' is set to 'LOCAL SERVICE, NETWORK SERVICE'"
  win_user_right:
    name: SeAssignPrimaryTokenPrivilege
    users:
        - LOCAL SERVICE
        - NETWORK SERVICE
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_44 is not defined or rule_2_2_44 is defined) and not rule_2_2_44
  tags:
    - level1
    - patch
    - rule_2.2.44

- name: "2.2.45 (L1) Ensure 'Restore files and directories' is set to 'Administrators'"
  win_user_right:
    name: SeRestorePrivilege
    users:
        - Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_45 is not defined or rule_2_2_45 is defined) and not rule_2_2_45
  tags:
    - level1
    - patch
    - rule_2.2.45

- name: "2.2.46 (L1) Ensure 'Shut down the system' is set to 'Administrators'"
  win_user_right:
    name: SeShutdownPrivilege
    users:
        - Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_46 is not defined or rule_2_2_46 is defined) and not rule_2_2_46
  tags:
    - level1
    - patch
    - rule_2.2.46

- name: "2.2.47 (L1) Ensure 'Synchronize directory service data' is set to 'No One' (DC only)"
  win_user_right:
    name: SeSyncAgentPrivilege
    users: []
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_47 is not defined or rule_2_2_47 is defined) and not rule_2_2_47
    - domain_joined_only is defined and domain_joined_only
  tags:
    - level1
    - patch
    - rule_2.2.47
    - domain_joined_only

- name: "2.2.48 (L1) Ensure 'Take ownership of files or other objects' is set to 'Administrators'"
  win_user_right:
    name: SeTakeOwnershipPrivilege
    users:
        - Administrators
    action: set
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_2_48 is not defined or rule_2_2_48 is defined) and not rule_2_2_48
  tags:
    - level1
    - patch
    - rule_2.2.48