---
- name: "18.5.8.1 (L1) Ensure 'Enable insecure guest logons' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\LanmanWorkstation
    name: AllowInsecureGuestAuth
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_5_8_1 is not defined or rule_18_5_8_1 is defined) and not rule_18_5_8_1
  tags:
    - level1
    - patch
    - rule_18.5.8.1

# - name: "18.5.9.1 (L2) Ensure Turn on Mapper I/O (LLTDIO) driver is set to Disabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\LLTD
#     name: "{{ item }}"
#     data: 0
#     type: dword
#   with_items:
#     - AllowLLTDIOOnDomain
#     - AllowLLTDIOOnPublicNet
#     - EnableLLTDIO
#     - ProhibitLLTDIOOnPrivateNet

# - name: "18.5.9.2 (L2) Ensure Turn on Responder (RSPNDR) driver is set to Disabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\LLTD
#     name: "{{ item }}"
#     data: 0
#     type: dword
#   with_items:
#     - AllowRspndrOnDomain
#     - AllowRspndrOnPublicNet
#     - EnableRspndr
#     - ProhibitRspndrOnPrivateNet

# - name: "18.5.10.2 (L2) Ensure Turn off Microsoft Peer-to-Peer Networking Services is set to Enabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\SOFTWARE\Policies\Microsoft\Peernet
#     name: Disabled
#     data: 1
#     type: dword

- name: "18.5.11.2 (L1) Ensure 'Prohibit installation and configuration of Network Bridge on your DNS domain network' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Network Connections
    name: NC_AllowNetBridge_NLA
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_5_11_2 is not defined or rule_18_5_11_2 is defined) and not rule_18_5_11_2
  tags:
    - level1
    - patch
    - rule_18.5.11.2

- name: "18.5.11.3 (L1) Ensure 'Prohibit use of Internet Connection Sharing on your DNS domain network' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Network Connections
    name: NC_ShowSharedAccessUI
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_5_11_3 is not defined or rule_18_5_11_3 is defined) and not rule_18_5_11_3
  tags:
    - level1
    - patch
    - rule_18.5.11.3

- name: "18.5.11.4 (L1) Ensure 'Require domain users to elevate when setting a network's location' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Network Connections
    name: NC_StdDomainUserSetLocation
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_5_11_4 is not defined or rule_18_5_11_4 is defined) and not rule_18_5_11_4
  tags:
    - level1
    - patch
    - rule_18.5.11.4

- name: "18.5.14.1 (L1)  Ensure 'Hardened UNC Paths' is set to 'Enabled, with 'Require Mutual Authentication' and 'Require Integrity' set for all NETLOGON and SYSVOL shares"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths
    name: "{{ item }}"
    data: 'RequireMutualAuthentication=1, RequireIntegrity=1'
    type: string
  with_items:
    - \\\\*\\NETLOGON
    - \\\\*\\SYSVOL
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_5_14_1 is not defined or rule_18_5_14_1 is defined) and not rule_18_5_14_1
  tags:
    - level1
    - patch
    - rule_18.5.14.1

# - name: "18.5.20.1 (L2) Ensure Configuration of wireless settings using Windows Connect Now is set to Disabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WCN\Registrars
#     name: "{{ item }}"
#     data: 0
#     type: dword
#   with_items:
#     - EnableRegistrars
#     - DisableWPDRegistrar
#     - DisableUPnPRegistrar
#     - DisableInBand802DOT11Registrar
#     - DisableFlashConfigRegistrar

# - name: "18.5.20.2 (L2) Ensure Prohibit access of the Windows Connect Now wizards is set to Enabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WCN\UI
#     name: DisableWcnUi
#     data: 1
#     type: dword
  
- name: "18.5.21.1 (L1) Ensure 'Minimize the number of simultaneous connections to the Internet or a Windows Domain' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WcmSvc\GroupPolicy
    name: fMinimizeConnections
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_5_21_1 is not defined or rule_18_5_21_1 is defined) and not rule_18_5_21_1
  tags:
    - level1
    - patch
    - rule_18.5.21.1

# - name: "18.5.21.2 (L2) Ensure Prohibit connection to non-domain networks when connected to domain authenticated network is set to Enabled"
#   win_regedit:
#     path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WcmSvc\GroupPolicy
#     name: fBlockNonDomain
#     data: 1
#     type: dword





