---
- name: "18.5.4.1 (L1) Ensure 'Turn off multicast name resolution' is set to 'Enabled' (MS Only)"
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows NT\DNSClient
    name: EnableMulticast
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_5_4_1 is not defined or rule_18_5_4_1 is defined) and not rule_18_5_4_1
  tags:
    - level1
    - patch
    - rule_18.5.4.1
