---
- name: "Obtain sub-keys of HKEY_USERS"
  win_reg_stat:
    path: HKU:\
  register: hku

- name: "19.5.1.1 (L1) Ensure 'Turn off toast notifications on the lock screen' is set to 'Enabled'"
  win_regedit:
    path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\PushNotifications
    name: NoToastApplicationNotificationOnLockScreen
    data: 1
    type: dword
  loop: "{{ hku.sub_keys | select('match', '^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$') | list }}"
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_19_5_1_1 is not defined or rule_19_5_1_1 is defined) and not rule_19_5_1_1
  tags:
    - level1
    - patch
    - rule_19.5.1.1
