---
- name: "17.9.1 (L1) Ensure 'Audit IPsec Driver' is set to 'Success and Failure'"
  win_command: 'auditpol /set /subcategory:"IPsec Driver" /success:enable /failure:enable'
  when: 
    - auditpol_data is not regex("\s*IPsec Driver\s*Success and Failure.*")
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_17_9_1 is not defined or rule_17_9_1 is defined) and not rule_17_9_1
  tags:
    - level1
    - patch
    - rule_17.9.1

- name: "17.9.2 (L1) Ensure 'Audit Other System Events' is set to 'Success and Failure'"
  win_command: 'auditpol /set /subcategory:"Other System Events" /success:enable /failure:enable'
  when: 
    - auditpol_data is not regex("\s*Other System Events\s*Success and Failure.*")
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_17_9_2 is not defined or rule_17_9_2 is defined) and not rule_17_9_2
  tags:
    - level1
    - patch
    - rule_17.9.2

- name: "17.9.3 (L1) Ensure 'Audit Security State Change' is set to 'Success'"
  win_command: 'auditpol /set /subcategory:"Security State Change" /success:enable /failure:disable'
  when: 
    - auditpol_data is not regex("\s*Security State Change\s*Success.*")
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_17_9_3 is not defined or rule_17_9_3 is defined) and not rule_17_9_3
  tags:
    - level1
    - patch
    - rule_17.9.3

- name: "17.9.4 (L1) Ensure 'Audit Security System Extension' is set to 'Success and Failure'"
  win_command: 'auditpol /set /subcategory:"Security System Extension" /success:enable /failure:disable'
  when: 
    - auditpol_data is not regex("\s*Security System Extension\s*Success.*")
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_17_9_4 is not defined or rule_17_9_4 is defined) and not rule_17_9_4
  tags:
    - level1
    - patch
    - rule_17.9.4

- name: "17.9.5 (L1) Ensure 'Audit System Integrity' is set to 'Success and Failure'"
  win_command: 'auditpol /set /subcategory:"System Integrity" /success:enable /failure:enable'
  when: 
    - auditpol_data is not regex("\s*System Integrity\s*Success and Failure.*")
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_17_9_5 is not defined or rule_17_9_5 is defined) and not rule_17_9_5
  tags:
    - level1
    - patch
    - rule_17.9.5


