---
- name: "2.3.15.1 (L1) Ensure 'System objects: Require case insensitivity for non-Windows subsystems' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Kernel
    name: ObCaseInsensitive
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_15_1 is not defined or rule_2_3_15_1 is defined) and not rule_2_3_15_1
  tags:
    - level1
    - patch
    - rule_2.3.15.1


- name: "2.3.15.2 (L1) Ensure 'System objects: Strengthen default permissions of internal system objects (e.g. Symbolic Links)' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager
    name: ProtectionMode
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_15_2 is not defined or rule_2_3_15_2 is defined) and not rule_2_3_15_2
  tags:
    - level1
    - patch
    - rule_2.3.15.2

