- name: "1.1.1 (L1) Ensure Enforce password history is set to 24 or more password(s)"
  win_security_policy:
    section: System Access
    key: PasswordHistorySize
    value: 24
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_1_1_1 is not defined or rule_1_1_1 is defined) and not rule_1_1_1
  tags:
    - level1
    - patch
    - rule_1.1.1

- name: "1.1.2 (L1) Ensure Maximum password age is set to 60 or fewer days, but not 0"
  win_security_policy:
    section: System Access
    key: MaximumPasswordAge
    value: 60
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_1_1_2 is not defined or rule_1_1_2 is defined) and not rule_1_1_2
  tags:
    - level1
    - patch
    - rule_1.1.2

- name: "1.1.3 (L1) Ensure Minimum password age is set to 1 or more day(s)"
  win_security_policy:
    section: System Access
    key: MinimumPasswordAge
    value: 1
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_1_1_3 is not defined or rule_1_1_3 is defined) and not rule_1_1_3
  tags:
    - level1
    - patch
    - rule_1.1.3

- name: "1.1.4 (L1) Ensure Minimum password length is set to 14 or more character(s)"
  win_security_policy:
    section: System Access
    key: MinimumPasswordLength
    value: 14
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_1_1_4 is not defined or rule_1_1_4 is defined) and not rule_1_1_4
  tags:
    - level1
    - patch
    - rule_1.1.4

- name: "1.1.5 (L1) Ensure Password must meet complexity requirements is set to Enabled"
  win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: 1
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_1_1_5 is not defined or rule_1_1_5 is defined) and not rule_1_1_5
  tags:
    - level1
    - patch
    - rule_1.1.5

- name: "1.1.6 (L1) Ensure Store passwords using reversible encryption is set to Disabled"
  win_security_policy:
    section: System Access
    key: ClearTextPassword
    value: 0
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_1_1_6 is not defined or rule_1_1_6 is defined) and not rule_1_1_6
  tags:
    - level1
    - patch
    - rule_1.1.6

- name: "1.2.2 (L1) Ensure Account lockout threshold is set to 10 or fewer invalid logon attempt(s), but not 0"
  win_security_policy:
    section: System Access
    key: LockoutBadCount
    value: 10
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_1_2_2 is not defined or rule_1_2_2 is defined) and not rule_1_2_2
    - non_domain_joined_only is defined and non_domain_joined_only
  tags:
    - level1
    - patch
    - rule_1.2.2
    - non_domain_joined_only

- name: "1.2.3 (L1) Ensure Reset account lockout counter after is set to 15 or more minute(s)"
  win_security_policy:
    section: System Access
    key: ResetLockoutCount
    value: 15
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_1_2_3 is not defined or rule_1_2_3 is defined) and not rule_1_2_3
    - non_domain_joined_only is defined and non_domain_joined_only
  tags:
    - level1
    - patch
    - rule_1.2.3
    - non_domain_joined_only

- name: "1.2.1 (L1) Ensure Account lockout duration is set to 15 or more minute(s)"
  win_security_policy:
    section: System Access
    key: LockoutDuration
    value: 15
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_1_2_1 is not defined or rule_1_2_1 is defined) and not rule_1_2_1
    - non_domain_joined_only is defined and non_domain_joined_only
  tags:
    - level1
    - patch
    - rule_1.2.1
    - non_domain_joined_only