---
- name: "2.3.2.1 (L1) Ensure 'Audit: Force audit policy subcategory settings (Windows Vista or later) to override audit policy category settings' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: SCENoApplyLegacyAuditPolicy
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_2_1 is not defined or rule_2_3_2_1 is defined) and not rule_2_3_2_1
  tags:
    - level1
    - patch
    - rule_2.3.2.1


- name: "2.3.2.2 (L1) Ensure 'Audit: Shut down system immediately if unable to log security audits' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: CrashOnAuditFail
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_2_2 is not defined or rule_2_3_2_2 is defined) and not rule_2_3_2_2
  tags:
    - level1
    - patch
    - rule_2.3.2.2

