---
- name: "18.1.1.1 (L1) Ensure 'Prevent enabling lock screen camera' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Personalization
    name: NoLockScreenCamera
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_1_1_1 is not defined or rule_18_1_1_1 is defined) and not rule_18_1_1_1
  tags:
    - level1
    - patch
    - rule_18.1.1.1

- name: "18.1.1.2 (L1) Ensure 'Prevent enabling lock screen slide show' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization
    name: NoLockScreenSlideshow
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_1_1_2 is not defined or rule_18_1_1_2 is defined) and not rule_18_1_1_2
  tags:
    - level1
    - patch
    - rule_18.1.1.2

- name: "18.1.2.2 (L1) Ensure Allow users to enable online speech recognition services is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\InputPersonalization
    name: AllowInputPersonalization
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_18_1_2_2 is not defined or rule_18_1_2_2 is defined) and not rule_18_1_2_2
  tags:
    - level1
    - patch
    - rule_18.1.2.2