---
- name: "2.3.10.1 (L1) Ensure 'Network access: Allow anonymous SID/Name translation' is set to 'Disabled'"
  win_security_policy:
    section: System Access
    key: LSAAnonymousNameLookup
    value: 0
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_10_1 is not defined or rule_2_3_10_1 is defined) and not rule_2_3_10_1
  tags:
    - level1
    - patch
    - rule_2.3.10.1


- name: "2.3.10.2 (L1) Ensure 'Network access: Do not allow anonymous enumeration of SAM accounts' is set to 'Enabled' (MS only)"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: RestrictAnonymousSAM
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_10_2 is not defined or rule_2_3_10_2 is defined) and not rule_2_3_10_2
  tags:
    - level1
    - patch
    - rule_2.3.10.2


- name: "2.3.10.3 (L1) Ensure 'Network access: Do not allow anonymous enumeration of SAM accounts and shares' is set to 'Enabled' (MS only)"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: RestrictAnonymous
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_10_3 is not defined or rule_2_3_10_3 is defined) and not rule_2_3_10_3
  tags:
    - level1
    - patch
    - rule_2.3.10.3


# - name: "2.3.10.4 (L2) Ensure 'Network access: Do not allow storage of passwords and credentials for network authentication' is set to 'Enabled'"
#   win_regedit:
#     path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
#     name: DisableDomainCreds
#     data: 1
#     type: dword

- name: "2.3.10.5 (L1) Ensure 'Network access: Let Everyone permissions apply to anonymous users' is set to 'Disabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: EveryoneIncludesAnonymous
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_10_5 is not defined or rule_2_3_10_5 is defined) and not rule_2_3_10_5
  tags:
    - level1
    - patch
    - rule_2.3.10.5


- name: "2.3.10.7 (L1) Configure 'Network access: Named Pipes that can be accessed anonymously'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
    name: NullSessionPipes
    data: ""
    type: string
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_10_7 is not defined or rule_2_3_10_7 is defined) and not rule_2_3_10_7
  tags:
    - level1
    - patch
    - rule_2.3.10.7


- name: "2.3.10.8 (L1) Configure 'Network access: Remotely accessible registry paths'"
  win_regedit:
    path: HKLM:\System\Currentcontrolset\Control\Securepipeservers\Winreg\AllowedExactpaths
    name: Machine
    data: ['System\CurrentControlSet\Control\ProductOptions', 'System\CurrentControlSet\Control\Server Applications', 'Software\Microsoft\Windows NT\CurrentVersion']
    type: multistring
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_10_8 is not defined or rule_2_3_10_8 is defined) and not rule_2_3_10_8
  tags:
    - level1
    - patch
    - rule_2.3.10.8

- name: "2.3.10.9 (L1) Configure 'Network access: Remotely accessible registry paths and sub-paths'"
  win_regedit:
    path: HKLM:\System\Currentcontrolset\Control\Securepipeservers\Winreg\Allowedpaths
    name: Machine
    data: ['System\CurrentControlSet\Control\Print\Printers', 'System\CurrentControlSet\Services\Eventlog', 'Software\Microsoft\OLAP Server', 'Software\Microsoft\Windows NT\CurrentVersion\Print', 'Software\Microsoft\Windows NT\CurrentVersion\Windows', 'System\CurrentControlSet\Control\ContentIndex', 'System\CurrentControlSet\Control\Terminal Server', 'System\CurrentControlSet\Control\Terminal Server\UserConfig', 'System\CurrentControlSet\Control\Terminal Server\DefaultUserConfiguration', 'Software\Microsoft\Windows NT\CurrentVersion\Perflib', 'System\CurrentControlSet\Services\SysmonLog']
    type: multistring
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_10_9 is not defined or rule_2_3_10_9 is defined) and not rule_2_3_10_9
  tags:
    - level1
    - patch
    - rule_2.3.10.9


- name: "2.3.10.10 (L1) Ensure 'Network access: Restrict anonymous access to Named Pipes and Shares' is set to 'Enabled'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
    name: RestrictNullSessAccess
    data: 1
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_10_10 is not defined or rule_2_3_10_10 is defined) and not rule_2_3_10_10
  tags:
    - level1
    - patch
    - rule_2.3.10.10


- name: "2.3.10.11 (L1) Ensure 'Network access: Restrict clients allowed to make remote calls to SAM' is set to 'Administrators: Remote Access: Allow' (MS only)"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: RestrictRemoteSAM
    data: "O:BAG:BAD:(A;;RC;;;BA)"
    type: string
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_10_11 is not defined or rule_2_3_10_11 is defined) and not rule_2_3_10_11
  tags:
    - level1
    - patch
    - rule_2.3.10.11


- name: "2.3.10.12 (L1) Ensure 'Network access: Shares that can be accessed anonymously' is set to 'None'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters
    name: NullSessionShares
    data: ""
    type: multistring
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_10_12 is not defined or rule_2_3_10_12 is defined) and not rule_2_3_10_12
  tags:
    - level1
    - patch
    - rule_2.3.10.12


- name: "2.3.10.13 (L1) Ensure 'Network access: Sharing and security model for local accounts' is set to 'Classic - local users authenticate as themselves'"
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: ForceGuest
    data: 0
    type: dword
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_2_3_10_13 is not defined or rule_2_3_10_13 is defined) and not rule_2_3_10_13
  tags:
    - level1
    - patch
    - rule_2.3.10.13
