---
- name: "Obtain sub-keys of HKEY_USERS"
  win_reg_stat:
    path: HKU:\
  register: hku

- name: "19.1.3.1 (L1) Ensure 'Enable screen saver' is set to 'Enabled'"
  win_regedit:
    path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop
    name: ScreenSaveActive
    data: '1'
    type: string
  loop: "{{ hku.sub_keys | select('match', '^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$') | list }}"
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_19_1_3_1 is not defined or rule_19_1_3_1 is defined) and not rule_19_1_3_1
  tags:
    - level1
    - patch
    - rule_19.1.3.1

- name: "19.1.3.2 (L1) Ensure 'Force specific screen saver: Screen saver executable name' is set to 'Enabled: scrnsave.scr'"
  win_regedit:
    path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop
    name: SCRNSAVE.EXE
    data: 'scrnsave.scr'
    type: string
  loop: "{{ hku.sub_keys | select('match', '^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$') | list }}"
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_19_1_3_2 is not defined or rule_19_1_3_2 is defined) and not rule_19_1_3_2
  tags:
    - level1
    - patch
    - rule_19.1.3.2

- name: "19.1.3.3 (L1) Ensure 'Password protect the screen saver' is set to 'Enabled'"
  win_regedit:
    path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop
    name: ScreenSaverIsSecure
    data: '1'
    type: string
  loop: "{{ hku.sub_keys | select('match', '^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$') | list }}"
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_19_1_3_3 is not defined or rule_19_1_3_3 is defined) and not rule_19_1_3_3
  tags:
    - level1
    - patch
    - rule_19.1.3.3

- name: "19.1.3.4 (L1)  Ensure 'Screen saver timeout' is set to 'Enabled: 900 seconds or fewer, but not 0'"
  win_regedit:
    path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop
    name: ScreenSaveTimeOut
    data: '900'
    type: string
  loop: "{{ hku.sub_keys | select('match', '^S-1-5-21-[0-9]+-[0-9]+-[0-9]+-[0-9]{3,}$') | list }}"
  when:
    - win2016cis_level1 is defined and win2016cis_level1
    - (rule_19_1_3_4 is not defined or rule_19_1_3_4 is defined) and not rule_19_1_3_4
  tags:
    - level1
    - patch
    - rule_19.1.3.4
