---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update package cache
      package: update_cache=yes
      changed_when: false
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2
  import_palybook: ../../../roles/DCE
  roles:
    - role: moleculemultiroles/roles/DCE/fooapp
  #roles:
    #- role: "DCE.fooapp"
