---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: instance
    image: ami-09c08b542a3df6eac
    image_owner: "801119661308"
    image_name: "amazon/Windows_Server-2022-English-Full-Base-2023.01.19"
    instance_type: t2.micro
    vpc_subnet_id: subnet-0cd6574a3c1f4a868
    user_data:  |
      <powershell>
      $url = "https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"
      $file = "$env:c\ConfigureRemotingForAnsible.ps1"
      (New-Object -TypeName System.Net.WebClient).DownloadFile($url, $file)
      powershell.exe -ExecutionPolicy ByPass -File $file -EnableCredSSP -Verbose

      $admin = [ADSI]("WinNT://./administrator, user")
      #$admin.SetPassword("mole12345%")
      $admin.SetPassword("{{ lookup('ansible.builtin.env', 'VM_PASSWORD_RESET') }}")

      #net user Administrator "mole12345%" 
      net user Administrator "{{ lookup('ansible.builtin.env', 'VM_PASSWORD_RESET') }}"
      </powershell>
    tags:
      Name: molecule_windows
    connection_options:
      sudo: true
      ansible_user: Administrator
      ansible_password: "{{ lookup('ansible.builtin.env', 'VM_PASSWORD_RESET') }}"
      #ansible_password: "mole12345%"
      ansible_port: 5986
      ansible_connection: winrm
      ansible_winrm_scheme: https
      ansible_winrm_server_cert_validation: ignore
      connection: winrm
provisioner:
  name: ansible
verifier:
  name: ansible

