---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Get whoami information
      win_whoami:

    - name: Stop service Tomcat123
      win_service:
        name: Tomcat8
        state: stopped
