---
name: Molecule Test for fooapp role
on:
  push:
    paths:
      - 'roles/Test/Newrole/**'
      - '.github/workflows/Newrole.yml'
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - 3.8
        collection_role:
          - Newrole
    steps:
      - uses: actions/checkout@v2
        with:
          path: moleculemultiroles
          
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
          
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install molecule ansible-core
          python3 -m pip install --upgrade --user setuptools
          python3 -m pip install --user "molecule[docker,lint]"
          ansible-galaxy collection install community.docker
      - name: Molecule Testing
        run: cd moleculemultiroles/roles/Test/Newrole && molecule test -s ${{ matrix.collection_role }}
        #run:  cd moleculemultiroles && molecule list -s ${{ matrix.collection_role }} && molecule create -s ${{ matrix.collection_role }} && molecule converge -s ${{ matrix.collection_role }} && molecule list -s ${{ matrix.collection_role }}
        

