---
name: path Test
on:
  push:
     paths: 
       - 'roles/**'
       - '.github/workflows/test.yml'
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - 3.8
        collection_role:
          - fooapp
        reponame:
          - moleculemultiroles
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            path1:
              - 'roles/DCE/fooapp/**'
            path2:
              - 'roles/Test/Newrole/**'
              
            
      - name: Run molecule Testing and install dependencies if conidtion statisfied
        if: steps.filter.outputs.path1 == 'true'
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install molecule ansible-core
          python3 -m pip install --upgrade --user setuptools
          python3 -m pip install --user "molecule[docker,lint]"
          ansible-galaxy collection install community.docker
          cd matrix.reponame/steps.filter.outputs.path1
          pwd

      

