---
name: Molecule Test for path Test
on:
  push:
    paths:
      - 'roles/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - 3.8
        collection_role:
          - fooapp
    steps:
      - uses: actions/checkout@v2
        id: filter
        with:
          path: moleculemultiroles
          filters: |
            path1:
              - 'roles/DCE/fooapp/**'
            path2:
              - 'roles/Test/Newrole/**'
      - name: path1 tests
        if: steps.filter.outputs.path1 == 'true'
        run: echo 'test'

