---
name: path Test
on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: filter
        with:
          filters: |
            path1:
              - 'roles/DCE/fooapp/**'
            path2:
              - 'roles/Test/Newrole/**'
              
      - name: path1 testing
        if: steps.filter.outputs.path1 == 'true'
        run: ansible --version

