---
name: path Test
on:
  push:
     paths: 
       - 'roles/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: filter
        with:
          filters: |
            path1:
              - 'roles/DCE/fooapp/**'
            path2:
              - 'roles/Test/Newrole/**'
              
      - name: path1 testing
        if: steps.filter.outputs.path1 == 'true'
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "::endgroup::"
      - name: simple evaluation on master
        if: github.ref == 'refs/heads/master'
        run: echo "runs"
        
      - name: simple evaluation on main
        if: github.ref == 'refs/heads/main'
        run: echo "runs"

