---
name: path Test
on:
  push:
     paths: 
       - 'roles/**'
       - '.github/workflows/test.yml'
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - 3.8
        collection_role:
          - fooapp
        reponame:
          - moleculemultiroles
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            path1:
              - 'roles/DCE/fooapp/**'
            path2:
              - 'roles/Test/Newrole/**'
            path3:
            - '.github/workflows/**'
              
            
      - name: Run molecule Testing and install dependencies if conidtion statisfied
        if: steps.filter.outputs.path3 == 'true'
        run: |
          ls
          pwd

      

